title: Your Blog Title
description: Your blog description
theme: jekyll-swiss
baseurl: ""
url: "https://yourusername.github.io"

# Swiss theme settings
theme_color: red # Can be red, blue, black, gray, magenta
