title: Nubia-labs blog
description: A space of discovery and sharing in AI
theme: jekyll-swiss
baseurl: ""
url: "https://nubia-labs.github.io"

# Swiss theme settings
theme_color: white # Can be red, blue, black, gray, magenta

# Author information
author:
  name: Nubia Labs
  email: hi@nubia-labs.com
  github: https://github.com/nubia-labs/
