title: Nubia-labs
description: A space of discovery and sharing in ML & AI
theme: jekyll-swiss
baseurl: ""
url: "https://nubia-labs.github.io"

theme_color: white

# Author information
author:
  name: Nubia Labs
  email: hi@nubia-labs.com
  github: https://github.com/nubia-labs/
  linkedin: https://www.linkedin.com/company/nubia-labs

# Social media links for theme
github_username: nubia-labs
linkedin_username: nubia-labs
twitter_username: nubia_labs  # if you want to add Twitter

# Site Author (for the "maintained by" text)
social_username: nubia-labs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# RSS Feed settings
feed:
  path: feed.xml
  posts_limit: 20
  excerpt_only: true

# Add this to your existing _config.yml
google_analytics: G-N2S3NLL66H

